#OBJS specifies which files to compile as part of the project
OBJS = 27_collision_detection.cpp

#OBJ_NAME specifies the name of our exectuable
OBJ_NAME = 27_collision_detection

#This is the target that compiles our executable
all : $(OBJS)
	g++ $(OBJS) -w -lSDL2 -lSDL2_image -o $(OBJ_NAME)
